language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install tensorflow h5py keras
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
