language: python
matrix:
  include:
    - python: 3.6
      env: KERAS_BACKEND=tensorflow
    - python: 3.6
      env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile
# command to install dependencies
install:
  - pip install tensorflow theano h5py keras
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
